level_0 = {'pos': (110,450), 'content': 'this is level 0', 'unlock':1}
level_1 = {'pos': (210,450), 'content': 'this is level 1', 'unlock':2}
level_2 = {'pos': (310,450), 'content': 'this is level 2', 'unlock':3}
level_3 = {'pos': (410,450), 'content': 'this is level 3', 'unlock':4}
level_4 = {'pos': (510,450), 'content': 'this is level 4', 'unlock':5}
level_5 = {'pos': (610,450), 'content': 'this is level 5', 'unlock':5}

levels = {0:level_0, 1:level_1, 2:level_2, 3:level_3, 4:level_4, 5:level_5}



levelsData = {
    0: [
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOGOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODOOOOOOCOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWO",
"GGGGGGGGGGGGGGGGGGBBGGGGGGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
],
    1: [
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOGGOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOGGOOOOOOOOOOOOOOOOOOOOOOODDOOOOOOOOOOOOOOOOO",
"OOOOOOOOOGGOOOOOOODDOOOOOOOOGGOOOOOOGGOOOOODDOOOOOOOOOOOOOOOOO",
"OPOOOOOOODDOOOOOOODDOOOOOOOODDOOOOOODDOOOOODDOOOCOOOOOOOOOOWOO",
"GGGGGBBBBDDBBBBBBBDDBBBBBBBBDDBBBBBBDDBBBBBDDBBBBBBBBBgggggggg",
        
],
    2: [
"OOOOOOOOOOOBBBBBBDDOOOOOOOOOOOOOOOOOOOOOBOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOBBBGGGDDOOOOOOOOOOOOOOOOOOOOOBOOOOOOOOOOOOOOOOOOOOO",
"OOPOOOOOOOOBBBDDDDDOOOBGGGGBBBBBBGGBBBOOBOOOOOOOOOOOOOOOOOOOOO",
"BGGGGGGBBOOBBBDDDDDOOOOOOOOOOOOOOBOOOOOOBOOOOOOOOOOOOOOOOOOOOO",
"BDDDDDDBBOOBBBDDDDDOOOOOOOOOOOOOOBOOOOOOBOOOOOOOOOOOOOOOOOOOOO",
"BOOOOOOOOOOOOBDDDDDBBBGBBBGOOOOOOBOOBBBBBOOOOOOOOOOOOOOOOOOOOO",
"BOOOOOOOOOOOCBDDDDDOOOOOOODOOOOOOBOOOOOOBOOOOOOOOOOOOOOOOOOOOO",
"BOOGGGGBBBBGGGBDDDDOOOOOOODOOOOOOBOOOOOOBOOOOOOOOOOOOOOOOOOOOO",
"BOOOOOOOOOOOBOOOOOOOOOOOOOOOOOOGGBOOOOOOBOOOOOOOOOOOOOOOOOOOOO",
"BOOOOOOOOOBOOOOOBpOOOOOOOOOOOOODDBOOOOOWBOOOOOOOOOOOOOOOOOOOOO",
"BOOOOGGGGGGGGGGGGGGOOOOOOOGGBBBDDBBBGGGGBOOOOOOOOOOOOOOOOOOOOO",
],
    
    3: [
"OOOOOOOOOOOOOOOBOOOOOOOOODBBBBBBBBBBBBBBOOOOOBBBBBBOODBBBBBBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOBOOOOOOOOOOOOOOROOOROOOOOOOOOOBDDDBBOODOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOBOOOOOOOOOOOOOOOOOOOOOOOOOOBBOBDDDBBOODOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOBOOBgggggggBBBBBBBBBBBBggOggBOBBOOOOOODOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWOOOO",
"OOOOOOOOOOOOOOOBOOBOOOOOOOOOOOOOOOOOOOOOOOOBCOOOOBBBODOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBGGGGGOOO",
"OOOOOOOOOOOOOOOBOOBOOOOOOOOOOOOOOOOOOOOOOOOBOOOOOBBOODOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOBOOBOOOOOOOOOOOOOOOOOOOOOOOOBBBBBBBBOOBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOBOOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOPOOOOOOOOOOOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOROOOBBOOOOoOOBOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"gggggggggggggggggggOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBOOBBBBBBBBBggggggOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"DDDDDDDDDDDDDDDDDDDOOOOOOOOOOOOOOOOOOOOggggOOOOggBBOOBBBOOOOOODDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOO",
],
    
    4: [
"OOOOOOBBBBBBBBGOOOOOOOOOOOOOOBBBBBBBBBBBBBBBBBBOOOOOOOOOOBOOOO",
"OOOOOOBBOOOOOOOOOOOOOOOOOOOOOBOOOOOOOOOOOOOOBOOOOOOOOOOOOBOOOO",
"OOOOOOBBORBBBBGGGGGGGGOOOBOROBOOOOOOOOOOOOOOOOOBBBBGGGGGOBOOOO",
"OOOOOOBBOOOOOOOOBOOOODGOOBOCOBOOOOOOOOOOOOOOOOOBOOOBBBBBOBOOOO",
"OOOOOOBBOOOOOOOOBOOOOOBOOBBBBBOOOOOROOOOOGGGGBBBOOOBOOOOOBOOOO",
"OOOOOOBBBBBBBBORBOOOOOBOOOOOOOOOOOOOOOOOOBOOOOOOOOOBOOOOOBOOOO",
"OOOOOOOOOOOOOOOOBOOOOOBOOOOOOOOOOOOOOOOOOBOOOOOOOOOBOBBBBBOOOO",
"OOOOOOOOOOOOOOOOBOOOOOBBBGGGGGOOOOOOOOOOOBOOOOOOOOOBOBOOOOOOOO",
"OOOOOOOOOOBBBBBBBOOOOOOOOOOOOBOOOOOOOOOOOBOOOOOOOOOBOBOOOOOOOO",
"OWOOOOOOOOBOOOOOBOOOOOOOOOOOOBOOOOOOOOOOOBOOOOOOOOOBOOOOOOOOPO",
"GGGGGGGGGGBBOOOOBOOOOOOOOOOOOBOOOOOOOOOOOBOOOOOOOOOGGGGGGGGGGG",
],
    
    5: [

"OOOOOOBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBDBBBBBBBBBOOO",
"OOOOOOBOOOOOOOOOOOOOOOOOOOOOOOBBBBBBBOOOOOOOOOOOBOOOOOOOOODOOO",
"OOOOOOBOOOOOOOOOBBBBBOOOOOOOOOBOOOOOBOOOOOOOOOOOBOBBBBBBBOBOOO",
"OOOOOOBOOOOOOOOOBOOOBOOOOOOOOOBOBOOOBOOOOOOOOOOOBOBOOOBOOOBOOO",
"OOOOOOBBBBBOOOOOBOBOBOOOOOOOOOBOBOOOBOOOOOOOBDBBBOBOOOOOOOBOOO",
"OOOOOOOOOOOOOOOOBOBOBBBBBBBOOOBOBBOOBOOOOOOOBOOOOOBOOOBOOOBOOO",
"OPOOOOOBOOOOBOOOOOBOOOOOOOBOOOBOBOOOBOOOOOOOBOBBBBBOBBBBBGBOOO",
"GGOOOOOBBOOBBBOOOOBGGGGGGOBBBBBOBOOOBOOOOOOOBOBOOOBOOOBOOOOOOO",
"DDGGGGBBBBBBBBBGGBBDDDDCOOOOOOOOBOBBDBBBBBBBBOBOOOBOOOOOOOOOOO",
"DDDDDDBBBBBBBBBDDBBDDDDBBBBOOOOOBOOOOOOOOOOOOOBOOOBOOOBOOOWOOO",
"DDDDDDBBBBBBBBBDDBBDDDDBBBBGGGGBBGGGGBBBBBBBBBBOOOBOOOBGGGGGGG",
],
    
}


tile_size = 64
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 11 * tile_size
LEVELS_AMOUNT = 5
SPRITE_SIDE = 32
FPS = 60

